; Feature override flags (for isolation testing).
; Set to 1 to enable a feature, 0 to disable it.
; This file is included after Util/macros.asm and overrides defaults.
; Generated by scripts/set_feature_flags.py.

!ENABLE_MINECART_CART_SHUTTERS       = 0
!ENABLE_MINECART_PLANNED_TRACK_TABLE = 1
!ENABLE_WATER_GATE_HOOKS             = 1
!ENABLE_WATER_GATE_OVERLAY_REDIRECT  = 1
!ENABLE_D3_PRISON_SEQUENCE           = 0
