; Module override flags (for isolation testing).
; Set to 1 to disable a module, 0 to enable it.
; This file is included after Util/macros.asm and overrides defaults.
; Generated by scripts/set_module_flags.py.

!DISABLE_MUSIC     = 0
!DISABLE_OVERWORLD = 0
!DISABLE_DUNGEON   = 0
!DISABLE_SPRITES   = 0
!DISABLE_MASKS     = 0
!DISABLE_ITEMS     = 0
!DISABLE_MENU      = 0
!DISABLE_PATCHES   = 0
