#!/usr/bin/env python3
"""
Mount Debug Context into AFS Knowledge Base

Aggregates debugging assets into a readable Markdown file for AI agents.
"""

import json
from pathlib import Path
import sys

# Add script dir to path
SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from mesen2_client_lib.client import OracleDebugClient
from mesen2_client_lib.constants import WATCH_PROFILES, WARP_LOCATIONS, ITEMS, STORY_FLAGS

def main():
    client = OracleDebugClient()
    manifest = client.get_library_manifest()
    
    output_path = Path(__file__).resolve().parents[1] / ".context" / "knowledge" / "debug_info.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, "w") as f:
        f.write("# Oracle Debugging Assets\n\n")
        f.write("This file is automatically generated. Do not edit.\n\n")
        
        f.write("## Canon States\n")
        f.write("| ID | Description | Location |\n")
        f.write("|----|-------------|----------|\n")
        for entry in manifest.get("entries", []):
            if entry.get("status") == "canon":
                f.write(f"| {entry['id']} | {entry.get('description', '')} | {entry.get('meta', {}).get('location', 'N/A')} |\n")
        f.write("\n")
        
        f.write("## Watch Profiles\n")
        f.write("| Profile | Description |\n")
        f.write("|---------|-------------|\n")
        for name, p in WATCH_PROFILES.items():
            f.write(f"| {name} | {p['description']} |\n")
        f.write("\n")
        
        f.write("## Warp Locations\n")
        f.write("| Name | Area | Position | Description |\n")
        f.write("|------|------|----------|-------------|\n")
        for name, loc in sorted(WARP_LOCATIONS.items()):
            f.write(f"| {name} | 0x{loc[0]:02X} | ({loc[1]}, {loc[2]}) | {loc[3]} |\n")
        f.write("\n")
        
        f.write("## Important Items\n")
        f.write("| Name | Description |\n")
        f.write("|------|-------------|\n")
        for name, (_, desc, _) in sorted(ITEMS.items()):
            f.write(f"| {name} | {desc} |\n")
        f.write("\n")
        
        f.write("## Story Flags\n")
        f.write("| Name | Description |\n")
        f.write("|------|-------------|\n")
        for name, (_, desc, _) in sorted(STORY_FLAGS.items()):
            f.write(f"| {name} | {desc} |\n")
            
    print(f"Mounted debug context to {output_path}")

if __name__ == "__main__":
    main()
