#!/usr/bin/env python3
"""Set feature enable flags for isolation builds.

Writes Config/feature_flags.asm to override Util/macros.asm defaults.
Feature flags are discovered from Util/macros.asm as !ENABLE_* defines.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


DEFINE_RE = re.compile(
    r"^\s*!([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(\$[0-9A-Fa-f]+|0x[0-9A-Fa-f]+|\d+)\b"
)


def _parse_int(token: str) -> int:
    token = token.strip()
    if token.startswith("$"):
        token = "0x" + token[1:]
    # Avoid Python's base=0 ambiguity with leading zeros (e.g. "02").
    if token.isdigit():
        return int(token, 10)
    return int(token, 0)


def _discover_features(macros_path: Path) -> tuple[list[str], dict[str, int]]:
    text = macros_path.read_text(encoding="utf-8", errors="ignore")
    features: list[str] = []
    defaults: dict[str, int] = {}
    for line in text.splitlines():
        m = DEFINE_RE.match(line)
        if not m:
            continue
        name = m.group(1).strip()
        if not name.startswith("ENABLE_"):
            continue
        value = _parse_int(m.group(2))
        defaults[name] = value
        features.append(name)
    features = sorted(set(features))
    return features, defaults


def _normalize(name: str) -> str:
    key = name.strip().upper().replace("-", "_")
    if not key:
        return key
    if not key.startswith("ENABLE_"):
        key = "ENABLE_" + key
    return key


def _render(features: list[str], values: dict[str, int]) -> str:
    lines = [
        "; Feature override flags (for isolation testing).",
        "; Set to 1 to enable a feature, 0 to disable it.",
        "; This file is included after Util/macros.asm and overrides defaults.",
        "; Generated by scripts/set_feature_flags.py.",
        "",
    ]
    width = max((len(f) for f in features), default=0)
    for feat in features:
        pad = " " * max(0, width - len(feat))
        lines.append(f"!{feat}{pad} = {int(values.get(feat, 0))}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Set feature enable flags for isolation builds")
    parser.add_argument("--disable", default="", help="Comma-separated features to disable (e.g. water_gate_hooks)")
    parser.add_argument("--enable", default="", help="Comma-separated features to enable (e.g. water_gate_hooks)")
    parser.add_argument(
        "--profile",
        choices=["all-on", "all-off", "defaults"],
        default="defaults",
        help="Apply a preset profile (defaults to Util/macros.asm values)",
    )
    parser.add_argument("--list", action="store_true", help="List discovered !ENABLE_* features and exit")
    parser.add_argument("--dry-run", action="store_true", help="Print output without writing file")
    parser.add_argument("--output", default="Config/feature_flags.asm", help="Output file path")
    parser.add_argument("--macros", default="Util/macros.asm", help="Path to macros file for feature discovery")
    args = parser.parse_args()

    macros_path = Path(args.macros)
    features, defaults = _discover_features(macros_path)
    if args.list:
        for feat in features:
            print(feat)
        return 0

    values: dict[str, int]
    if args.profile == "all-on":
        values = {f: 1 for f in features}
    elif args.profile == "all-off":
        values = {f: 0 for f in features}
    else:
        values = dict(defaults)

    def apply_list(raw: str, target: int) -> None:
        if not raw:
            return
        for token in raw.split(","):
            key = _normalize(token)
            if not key:
                continue
            if key not in features:
                raise SystemExit(f"Unknown feature: {token} (expected one of: {', '.join(features)})")
            values[key] = target

    apply_list(args.disable, 0)
    apply_list(args.enable, 1)

    output = Path(args.output)
    content = _render(features, values)
    if args.dry_run:
        print(content)
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
