#!/usr/bin/env python3
"""Set module disable flags for isolation builds.

Writes Config/module_flags.asm to override Util/macros.asm defaults.
"""
from __future__ import annotations

import argparse
from pathlib import Path

MODULES = [
    "music",
    "overworld",
    "dungeon",
    "sprites",
    "masks",
    "items",
    "menu",
    "patches",
]

ALIASES = {
    "ow": "overworld",
    "uw": "dungeon",
    "dgn": "dungeon",
    "spr": "sprites",
    "gfx": "sprites",
    "hud": "menu",
    "ui": "menu",
}

PROFILES = {
    "all": {},
    "core-only": {m: 1 for m in MODULES},
    "no-overworld": {"overworld": 1},
    "no-dungeon": {"dungeon": 1},
    "no-sprites": {"sprites": 1},
    "no-menu": {"menu": 1},
    "no-items": {"items": 1},
    "no-masks": {"masks": 1},
    "no-patches": {"patches": 1},
}


def normalize(name: str) -> str:
    key = name.strip().lower()
    return ALIASES.get(key, key)


def render(flags: dict[str, int]) -> str:
    lines = [
        "; Module override flags (for isolation testing).",
        "; Set to 1 to disable a module, 0 to enable it.",
        "; This file is included after Util/macros.asm and overrides defaults.",
        "; Generated by scripts/set_module_flags.py.",
        "",
    ]
    for module in MODULES:
        const = f"!DISABLE_{module.upper():<9}"
        lines.append(f"{const} = {flags[module]}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Set module disable flags for isolation builds")
    parser.add_argument("--disable", default="", help="Comma-separated modules to disable")
    parser.add_argument("--enable", default="", help="Comma-separated modules to enable")
    parser.add_argument("--profile", choices=sorted(PROFILES), help="Apply a preset profile")
    parser.add_argument("--dry-run", action="store_true", help="Print flags without writing file")
    parser.add_argument("--output", default="Config/module_flags.asm", help="Output file path")
    args = parser.parse_args()

    flags = {m: 0 for m in MODULES}

    if args.profile:
        preset = PROFILES[args.profile]
        for mod, value in preset.items():
            flags[mod] = int(value)

    def apply_list(value: str, target: int) -> None:
        if not value:
            return
        for raw in value.split(","):
            name = normalize(raw)
            if not name:
                continue
            if name not in MODULES:
                raise SystemExit(f"Unknown module: {raw}")
            flags[name] = target

    apply_list(args.disable, 1)
    apply_list(args.enable, 0)

    output = Path(args.output)
    content = render(flags)

    if args.dry_run:
        print(content)
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
