; =========================================================
; Dungeon Map Layouts
; Generated by Yaze and included here.
; =========================================================

; D1: Mushroom Grotto
; org $2Cxxxx ; Set address if hardcoding or allow dynamic placement
; incbin "Maps/d1_mushroom_grotto.bin"

; D2: Tail Palace
; incbin "Maps/d2_tail_palace.bin"

; D3: Kalyxo Castle
; incbin "Maps/d3_kalyxo_castle.bin"

; D4: Zora Temple
; incbin "Maps/d4_zora_temple.bin"

; D5: Glacia Estate
; incbin "Maps/d5_glacia_estate.bin"

; D6: Goron Mines
; incbin "Maps/d6_goron_mines.bin"

; D7: Dragon Ship
; incbin "Maps/d7_dragon_ship.bin"

; D8: Fortress of Secrets
; incbin "Maps/d8_fortress_of_secrets.bin"

; S1: Shrine of Wisdom
; incbin "Maps/s1_shrine_of_wisdom.bin"

; S2: Shrine of Power
; incbin "Maps/s2_shrine_of_power.bin"

; S3: Shrine of Courage
; incbin "Maps/s3_shrine_of_courage.bin"
