OverworldLocationNames:
  dw "RANCH___________" ; 00
  dw "RANCH___________" ; 01
  dw "PYRAMID_________" ; 02
  dw "LAND_OF_TREE____" ; 03
  dw "SNOW_MOUNTAIN___" ; 04 
  dw "SNOW_MOUNTAIN___" ; 05 
  dw "SNOW_MOUNTAIN___" ; 06
  dw "SNOW_MOUNTAIN___" ; 07
  dw "RANCH___________" ; 08
  dw "RANCH___________" ; 09
  dw "INN_____________" ; 0A
  dw "KALYXO_CASTLE___" ; 0B
  dw "KALYXO_CASTLE___" ; 0C
  dw "POTION_SHOP_____" ; 0D
  dw "HALL_OF_SECRETS_" ; 0E
  dw "CEMETERY________" ; 0F
  dw "TOADSTOOL_WOODS_" ; 10
  dw "RANCH_PATH______" ; 11
  dw "CROSSROADS______" ; 12 
  dw "KALYXO_CASTLE___" ; 13
  dw "KALYXO_CASTLE___" ; 14
  dw "MOUNTAINSIDE____" ; 15
  dw "PATH_OF_SECRETS_" ; 16
  dw "ANCIENT_SHRINE__" ; 17
  dw "TOADSTOOL_WOODS_" ; 18
  dw "TOADSTOOL_WOODS_" ; 19
  dw "CROSSROADS______" ; 1A
  dw "KALYXO_CASTLE___" ; 1B
  dw "KALYXO_ROAD_____" ; 1C
  dw "CROSSROADS______" ; 1D
  dw "SUNKEN_CITY_____" ; 1E
  dw "SUNKEN_CITY_____" ; 1F
  dw "TOADSTOOL_WOODS_" ; 20
  dw "TOADSTOOL_WOODS_" ; 21
  dw "SWORDSMITHS_____" ; 22
  dw "WAYWARD_VILLAGE_" ; 23
  dw "WAYWARD_VILLAGE_" ; 24
  dw "VILLAGE_ROAD____" ; 25
  dw "SUNKEN_CITY_____" ; 26
  dw "SUNKEN_CITY_____" ; 27
  dw "TOADSTOOL_WOODS_" ; 28
  dw "TOADSTOOL_WOODS_" ; 29
  dw "VILLAGE_ROAD____" ; 2A
  dw "WAYWARD_VILLAGE_" ; 2B
  dw "WAYWARD_VILLAGE_" ; 2C
  dw "VALLEY__________" ; 2D
  dw "CITY_ROAD_______" ; 2E
  dw "TAIL_PALACE_____" ; 2F
  dw "PHANTOM_SHIP____" ; 30
  dw "PHANTOM_SHIP____" ; 31
  dw "SECRET_BEACH____" ; 32
  dw "LOOM_BEACH______" ; 33
  dw "LOOM_BEACH______" ; 34
  dw "BEACH_PATH______" ; 35
  dw "GARO_DESERT_____" ; 36
  dw "GARO_DESERT_____" ; 37
  dw "PHANTOM_SHIP____" ; 38
  dw "PHANTOM_SHIP____" ; 39
  dw "LOST_SEA________" ; 3A
  dw "LOOM_BEACH______" ; 3B
  dw "LOOM_BEACH______" ; 3C
  dw "LOOM_WATERFALL__" ; 3D
  dw "GARO_DESERT_____" ; 3E
  dw "GARO_DESERT_____" ; 3F